// Inkline extension configuration.
//
// The "key" field in manifest.json pins the extension ID for everyone who
// loads this folder unpacked, so the native-messaging host manifest written by
// scripts/install-native-host.sh works out of the box. The key is a public
// key; there is nothing secret about it.

const INKLINE_CONFIG = {
  // Hosted notary the helper is enrolled against (informational — the
  // extension never contacts it; the helper stores the URL at enroll time).
  NOTARY_URL: 'https://inkline-notary-production.up.railway.app',

  // Where the Verify link in the email footer points (the hosted verifier).
  // Local testing: run `python3 -m http.server 8000` from the repository
  // root and use http://localhost:8000/verifier/.
  VERIFY_URL: 'https://verify.inklineverify.com/verifier/',

  // Default stamp graphic shown before the footer text (14x14 px). Must be a
  // hosted PNG (Gmail strips SVG and data: images in received mail); it ships
  // in verifier/ so it deploys with the verify page. Set to '' for a
  // text-only footer.
  STAMP_IMG: 'https://verify.inklineverify.com/verifier/inklinestamp.png',

  // Directory holding the coloured stamp variants (verifier/stamps/*.png,
  // generated by scripts/make-stamps.py). Users pick one on the extension's
  // options page; deployed alongside STAMP_IMG.
  STAMP_DIR: 'https://verify.inklineverify.com/verifier/stamps/',
};
