// Regenerates canonical/vectors.json — the cross-implementation ground truth.
// Both the Node test suite and the Swift test suite assert byte-identical
// results against this file. Run: npm run vectors
//
// canonical/test-key.jwk.json is a fixed P-256 keypair used ONLY to produce
// signature vectors. It is intentionally public and must never be used for
// anything but tests.

import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { cjson } from '../shared/cjson.js';
import { canonText, canonicalEmail, emailContentHash } from '../shared/canonical.js';
import { b64uEncode } from '../shared/b64.js';
import { presenceSignInput, kidOfPub } from '../shared/receipt.js';

const subtle = globalThis.crypto.subtle;
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'canonical');
mkdirSync(outDir, { recursive: true });

const cjsonCases = [
  { value: null, expected: 'null' },
  { value: true, expected: 'true' },
  { value: 0, expected: '0' },
  { value: -42, expected: '-42' },
  { value: 'plain', expected: '"plain"' },
  { value: 'quote " backslash \\', expected: '"quote \\" backslash \\\\"' },
  { value: 'tab\tnewline\ncr\r', expected: '"tab\\tnewline\\ncr\\r"' },
  { value: 'nul' + String.fromCharCode(0) + 'unit' + String.fromCharCode(1) + 'sep' + String.fromCharCode(31), expected: '"nul\\u0000unit\\u0001sep\\u001f"' },
  { value: 'café 日本語 😀', expected: '"café 日本語 😀"' },
  { value: [1, 'two', null, [true]], expected: '[1,"two",null,[true]]' },
  {
    value: { z: 1, a: 2, mid: { beta: 'b', Alpha: 'a' } },
    expected: '{"a":2,"mid":{"Alpha":"a","beta":"b"},"z":1}',
  },
  {
    value: { v: 1, action: 'email', kid: 'K', nonce: 'N', iat: 1700000000, contentHash: 'H' },
    expected: '{"action":"email","contentHash":"H","iat":1700000000,"kid":"K","nonce":"N","v":1}',
  },
];

const canonTextCases = [
  { input: '', expected: '' },
  { input: 'Hello World', expected: 'hello world' },
  { input: '  MIXED   Case\tText \r\n line two \r\n\r\n line three  ', expected: 'mixed case text line two line three' },
  { input: 'non breaking spaces　here', expected: 'non breaking spaces here' },
  { input: 'zero﻿width-bom', expected: 'zero width-bom' },
  // e + combining acute vs precomposed must land on the same bytes
  { input: 'Café CAFÉ', expected: 'café café' },
  { input: 'A B C', expected: 'a b c' },
];

const emailCases = [
  {
    email: {
      from: 'Sender@Example.com ',
      to: ['Alice@example.COM', ' bob@example.com'],
      cc: [],
      subject: '  Meeting   Tomorrow ',
      body: 'Hi Alice,\r\n\r\nSee you at   10am.\r\n— Sender',
    },
  },
  {
    email: {
      from: 'a@b.c',
      to: [],
      cc: ['cÉdric@example.com'],
      subject: '',
      body: 'plain',
    },
  },
];

for (const c of emailCases) {
  c.canonicalJson = cjson(canonicalEmail(c.email));
  c.contentHash = await emailContentHash(c.email);
}

// ---- signature vector ----------------------------------------------------
const keyPath = join(outDir, 'test-key.jwk.json');
let keyFile;
if (existsSync(keyPath)) {
  keyFile = JSON.parse(readFileSync(keyPath, 'utf8'));
} else {
  const pair = await subtle.generateKey({ name: 'ECDSA', namedCurve: 'P-256' }, true, ['sign', 'verify']);
  keyFile = {
    comment: 'TEST VECTOR KEY ONLY. Deliberately public. Never use outside tests.',
    priv: await subtle.exportKey('jwk', pair.privateKey),
    pub: b64uEncode(new Uint8Array(await subtle.exportKey('raw', pair.publicKey))),
  };
  writeFileSync(keyPath, JSON.stringify(keyFile, null, 2) + '\n');
}

const priv = await subtle.importKey('jwk', keyFile.priv, { name: 'ECDSA', namedCurve: 'P-256' }, false, ['sign']);
const payload = {
  v: 1,
  action: 'email',
  contentHash: emailCases[0].contentHash,
  nonce: 'dGVzdC1ub25jZS10ZXN0LW5vbmNlLXRlc3Qtbm9uY2Vh',
  iat: 1756339200,
  kid: await kidOfPub(keyFile.pub),
};
const signInput = presenceSignInput(payload);
const sig = new Uint8Array(await subtle.sign({ name: 'ECDSA', hash: 'SHA-256' }, priv, signInput));

const vectors = {
  comment:
    'Golden vectors for Inkline canonical JSON, canonical email v1, and the presence signing input. Generated by scripts/gen-vectors.mjs; asserted byte-for-byte by both the Node and Swift test suites.',
  cjson: cjsonCases,
  canonText: canonTextCases,
  emails: emailCases,
  presence: {
    pub: keyFile.pub,
    payload,
    signInput: b64uEncode(signInput),
    sig: b64uEncode(sig),
  },
};

writeFileSync(join(outDir, 'vectors.json'), JSON.stringify(vectors, null, 2) + '\n');
console.log('wrote canonical/vectors.json');
