// Apple App Attest verification (server side), per
// https://developer.apple.com/documentation/devicecheck/validating-apps-that-connect-to-your-server
//
// verifyAttestation: one-time enrollment proof that a key was generated by a
// genuine Apple device inside a legitimately signed app.
// verifyAssertion: per-request proof, with a monotonic counter for replay
// protection.

import { X509Certificate, createHash, createPublicKey, verify as cryptoVerify } from 'node:crypto';
import { cborDecode } from './cbor.js';
import { extractAppAttestNonce } from './asn1.js';

// aaguid is 16 bytes: "appattest" zero-padded (production) or
// "appattestdevelop" (development sandbox).
const AAGUID_PRODUCTION = Uint8Array.from([
  ...new TextEncoder().encode('appattest'), 0, 0, 0, 0, 0, 0, 0,
]);
const AAGUID_DEVELOPMENT = new TextEncoder().encode('appattestdevelop');

export function sha256(bytes) {
  return new Uint8Array(createHash('sha256').update(bytes).digest());
}

export function appIdHash(appId) {
  return sha256(new TextEncoder().encode(appId));
}

function bytesEqual(a, b) {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];
  return diff === 0;
}

function readU32BE(b, o) {
  return b[o] * 0x1000000 + ((b[o + 1] << 16) | (b[o + 2] << 8) | b[o + 3]);
}

function rawPointFromSpki(spkiDer) {
  // For P-256 the SPKI ends with the uncompressed point: 0x04 || X || Y.
  const point = spkiDer.subarray(spkiDer.length - 65);
  if (point[0] !== 0x04) throw new Error('appattest: unexpected public key form');
  return new Uint8Array(point);
}

function verifyChainToRoot(certs, rootPem, now) {
  const root = new X509Certificate(rootPem);
  const chain = [...certs, root];
  for (let i = 0; i < chain.length; i++) {
    const cert = chain[i];
    if (now < new Date(cert.validFrom) || now > new Date(cert.validTo)) {
      throw new Error('appattest: certificate outside validity window');
    }
    const issuer = i + 1 < chain.length ? chain[i + 1] : chain[i];
    if (cert.issuer !== issuer.subject) {
      throw new Error('appattest: certificate chain broken (issuer mismatch)');
    }
    if (!cert.verify(issuer.publicKey)) {
      throw new Error('appattest: certificate chain signature invalid');
    }
  }
}

// attestation: Uint8Array (CBOR attestation object)
// clientDataHash: Uint8Array(32) — SHA-256 of the client data the app attested
// keyId: Uint8Array(32) — the App Attest key identifier the client claims
// appId: "TEAMID.bundle.id"
// rootPem: trusted root CA (Apple's in production; a fixture CA in tests)
//
// Both Apple environments are accepted (the environment entitlement is not
// grantable for Developer ID Mac apps, so which one a device attests in is
// discovered at runtime); the detected environment is returned so callers
// can record and log it.
export function verifyAttestation({ attestation, clientDataHash, keyId, appId, rootPem, now = new Date() }) {
  let obj;
  try {
    obj = cborDecode(attestation);
  } catch {
    throw new Error('appattest: attestation is not valid CBOR');
  }
  if (obj?.fmt !== 'apple-appattest') throw new Error('appattest: unexpected format');
  const x5c = obj.attStmt?.x5c;
  const authData = obj.authData;
  if (!Array.isArray(x5c) || x5c.length < 2 || !(authData instanceof Uint8Array)) {
    throw new Error('appattest: malformed attestation statement');
  }

  const certs = x5c.map((der) => {
    if (!(der instanceof Uint8Array)) throw new Error('appattest: malformed x5c');
    return new X509Certificate(Buffer.from(der));
  });
  verifyChainToRoot(certs, rootPem, now);

  // Nonce binds the certificate to this exact attestation request.
  const expectedNonce = sha256(Buffer.concat([authData, clientDataHash]));
  const certNonce = extractAppAttestNonce(new Uint8Array(certs[0].raw));
  if (!certNonce || !bytesEqual(certNonce, expectedNonce)) {
    throw new Error('appattest: nonce mismatch');
  }

  // The key identifier is the SHA-256 of the credential public key.
  const spki = new Uint8Array(certs[0].publicKey.export({ type: 'spki', format: 'der' }));
  const pubRaw = rawPointFromSpki(spki);
  if (!bytesEqual(sha256(pubRaw), keyId)) {
    throw new Error('appattest: keyId does not match credential public key');
  }

  // Authenticator data: rpIdHash(32) || flags(1) || counter(4) ||
  //   aaguid(16) || credIdLen(2) || credId(32)
  if (authData.length < 87) throw new Error('appattest: authData too short');
  if (!bytesEqual(authData.subarray(0, 32), appIdHash(appId))) {
    throw new Error('appattest: RP ID hash does not match app ID');
  }
  if (readU32BE(authData, 33) !== 0) throw new Error('appattest: nonzero initial counter');
  const aaguid = authData.subarray(37, 53);
  let environment;
  if (bytesEqual(aaguid, AAGUID_PRODUCTION)) environment = 'production';
  else if (bytesEqual(aaguid, AAGUID_DEVELOPMENT)) environment = 'development';
  else throw new Error('appattest: unknown attestation environment');
  const credIdLen = (authData[53] << 8) | authData[54];
  if (credIdLen !== 32 || !bytesEqual(authData.subarray(55, 87), keyId)) {
    throw new Error('appattest: credential ID does not match keyId');
  }

  return {
    attestPubSpki: spki,
    counter: 0,
    environment,
  };
}

// assertion: Uint8Array (CBOR { signature, authenticatorData })
// clientData: Uint8Array — the exact bytes the app asserted over
// attestPubSpki: Uint8Array — SPKI DER stored at enrollment
// prevCounter: last accepted counter for this key
export function verifyAssertion({ assertion, clientData, appId, attestPubSpki, prevCounter }) {
  let obj;
  try {
    obj = cborDecode(assertion);
  } catch {
    throw new Error('appattest: assertion is not valid CBOR');
  }
  const sig = obj?.signature;
  const authData = obj?.authenticatorData;
  if (!(sig instanceof Uint8Array) || !(authData instanceof Uint8Array) || authData.length < 37) {
    throw new Error('appattest: malformed assertion');
  }

  const clientDataHash = sha256(clientData);
  const key = createPublicKey({ key: Buffer.from(attestPubSpki), format: 'der', type: 'spki' });
  const ok = cryptoVerify('sha256', Buffer.concat([authData, clientDataHash]), key, Buffer.from(sig));
  if (!ok) throw new Error('appattest: assertion signature invalid');

  if (!bytesEqual(authData.subarray(0, 32), appIdHash(appId))) {
    throw new Error('appattest: assertion RP ID hash mismatch');
  }
  const counter = readU32BE(authData, 33);
  if (counter <= prevCounter) throw new Error('appattest: assertion counter replay');

  return { counter };
}
